### ISSUE TITLE
Filter alerts 'zpool_status'

### ISSUE THREAD

**Issue by dmoity** [gfriloux/botman#9]
Alfred can trace many alerts, some are more important as the degraded status. It would be interesting to filter the alerts. For example don't display alerts like :
Alfred : Received an alert from xxx () : Variable 'zpool_status' changed from '(null)' to 'ONLINE'

**Comment by gfriloux** [comment]
Wrong project.
Issue opened at https://github.com/gfriloux/gotham-module-alert/issues/1
